//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsankKrushi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerDOB { get; set; }
        public string FieldArea { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string AadharNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string Photo { get; set; }
    }
}
