//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsankKrushi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int Id { get; set; }
        public string Productcategory { get; set; }
        public string Productname { get; set; }
        public string Unittopurchase { get; set; }
        public string Distributorname { get; set; }
        public string Distributoraddress { get; set; }
        public string Rateofpreviousorder { get; set; }
    }
}
